name: Update RSS Feed

on:
  push:
    branches: 
      - main
  schedule:
    - cron: "*/5 * * * *" # Run every day at midnight

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Delete rss_feed.xml
      run: python delete_rss_feed.py

    - name: Generate rss_feed.xml
      run: python update_rss.py
    
    - name: Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add rss_feed.xml
          git commit -m "Update RSS Feed"
          git push
   
